### ISSUE TITLE
IBM Cloud CLI does not set the ssh key at VM creation

### ISSUE THREAD

**Issue by ochamber** [IBM-Cloud/ibm-cloud-cli-release#57] opened 2018-09-14 08:10 UTC
Hi,

Using the following command to provision this server:
# ibmcloud sl vs create --hostname icpmgm001 --domain mydomain.com --datacenter dal13 --cpu 8 --memory 16 --os CENTOS_7_64 --key 1188623 --force
The ssh key is not set on the vm once built.  It works when selecting the key via ui.

Regards. Olivier.

**Comment by sbockelman** [comment] 2018-09-14 13:33
Using -k instead of --key does work

**Comment by boyang9527** [comment] 2018-09-14 18:33
@youhwsh@cn.ibm.com
pls take a look at it

**Comment by YouHang** [comment] 2018-09-15 03:07
Hi @ochamber @sbockelman , which ibmcloud version do you use? I can't reproduce this on my side.

Also, can you please post the trace log here by using 'ibmcloud config --trace=true'

**Comment by ochamber** [comment] 2018-09-17 14:41
Hi,

#ibmcloud --version
ibmcloud version 0.9.0+929f34d-2018-08-21T07:17:55+00:00

root@olivier-VB:~# ibmcloud config --trace=true

Option 1
root@olivier-VB:~# ibmcloud sl vs create --hostname icpmgm001-ho --domain irblab.com --datacenter fra02 --cpu 8 --memory 16 --os CENTOS_7_64 --key 1184733 --force
2018/09/17 11:37:42 [DEBUG] Request URL:  POST https://api.softlayer.com/mobile/v3.1/SoftLayer_Virtual_Guest.json
2018/09/17 11:37:42 [DEBUG] Parameters:  {"parameters":[{"datacenter":{"name":"fra02"},"dedicatedAccountHostOnlyFlag":false,"domain":"irblab.com","hostname":"icpmgm001-ho","hourlyBillingFlag":true,"localDiskFlag":true,"maxMemory":16,"operatingSystemReferenceCode":"CENTOS_7_64","privateNetworkOnlyFlag":false,"startCpus":8}]}
2018/09/17 11:37:48 [DEBUG] Status Code:  201
2018/09/17 11:37:48 [DEBUG] Response:  {"accountId":1687615,"createDate":"2018-09-17T04:48:15-05:00","domain":"irblab.com","fullyQualifiedDomainName":"icpmgm001-ho.irblab.com","hostname":"icpmgm001-ho","id":61732767,"lastPowerStateId":null,"lastVerifiedDate":null,"maxCpu":8,"maxCpuUnits":"CORE","maxMemory":16384,"metricPollDate":null,"modifyDate":null,"provisionDate":null,"startCpus":8,"statusId":1001,"uuid":"e52a36e0-a289-4352-9d56-e4bcf7093f75","globalIdentifier":"6bf4d4ad-cdc1-458a-a26d-7b381fc5d86f"}
name      value   
ID        61732767   
FQDN      icpmgm001-ho.irblab.com   
created   2018-09-17T09:48:15Z   
guid      6bf4d4ad-cdc1-458a-a26d-7b381fc5d86f   

Option 2
root@olivier-VB:~# ibmcloud sl vs create --hostname icpmgm002-ho --domain irblab.com --datacenter fra02 --cpu 8 --memory 16 --os CENTOS_7_64 -k 1184733 --force
2018/09/17 15:24:19 [DEBUG] Request URL:  POST https://api.softlayer.com/mobile/v3.1/SoftLayer_Virtual_Guest.json
2018/09/17 15:24:19 [DEBUG] Parameters:  {"parameters":[{"datacenter":{"name":"fra02"},"dedicatedAccountHostOnlyFlag":false,"domain":"irblab.com","hostname":"icpmgm002-ho","hourlyBillingFlag":true,"localDiskFlag":true,"maxMemory":16,"operatingSystemReferenceCode":"CENTOS_7_64","privateNetworkOnlyFlag":false,"sshKeys":[{"id":1184733}],"startCpus":8}]}
2018/09/17 15:24:24 [DEBUG] Status Code:  201
2018/09/17 15:24:24 [DEBUG] Response:  {"accountId":1687615,"createDate":"2018-09-17T08:24:22-05:00","domain":"irblab.com","fullyQualifiedDomainName":"icpmgm002-ho.irblab.com","hostname":"icpmgm002-ho","id":61744877,"lastPowerStateId":null,"lastVerifiedDate":null,"maxCpu":8,"maxCpuUnits":"CORE","maxMemory":16384,"metricPollDate":null,"modifyDate":null,"provisionDate":null,"startCpus":8,"statusId":1001,"uuid":"67b16f61-b3ea-4767-93e6-b9ba3d8c95a2","globalIdentifier":"3007c56b-4561-4ff9-99c0-2ba84089f537"}
name      value   
ID        61744877   
FQDN      icpmgm002-ho.irblab.com   
created   2018-09-17T13:24:22Z   
guid      3007c56b-4561-4ff9-99c0-2ba84089f537

icpmgm001-ho.irblab.com - 158.177.65.157 
icpmgm002-ho.irblab.com - 158.177.65.147

#ssh root@158.177.65.157
The authenticity of host '158.177.65.157 (158.177.65.157)' can't be established.
ECDSA key fingerprint is SHA256:ofVwydZN9ygvHZDGms6PJnj6jeCN00j9B9LSnHWaJOk.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '158.177.65.157' (ECDSA) to the list of known hosts.
root@158.177.65.157's password: 
Last failed login: Mon Sep 17 05:12:33 CDT 2018 from 66.35.51.199 on ssh:notty
There were 6 failed login attempts since the last successful login.
[root@icpmgm001-ho ~]# 

MacBook-de-Olivier:.ssh ochamberaud$ ssh root@158.177.65.147
The authenticity of host '158.177.65.147 (158.177.65.147)' can't be established.
ECDSA key fingerprint is SHA256:LVY1gq7pkiXrzqrh6lVfmSSl9aV4jkyGlj9SlQuZFt0.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '158.177.65.147' (ECDSA) to the list of known hosts.
[root@icpmgm002-ho ~]#

in option 1, I need to type the server password while I don't need to do it in option2.
So as stated by Scott, -k is working fine while --key is not

#ibmcloud sl vs create --help
Options shows
   -k value, --key value                     The IDs of the SSH keys to add to the root user (multiple occurrence permitted)
So both option should work. Hope it helps.

**Comment by YouHang** [comment] 2018-09-18 02:17
Thanks!  @ochamber We are working on it

**Comment by YouHang** [comment] 2018-09-18 02:54
It has been fixed. we will add this fix in the next release version.
Currently, you can use -k to work around...

**Comment by boyang9527** [comment] 2018-10-26 18:50
close this issue given it is fixed

**Closed by boyang9527** 2018-10-26 18:50 UTC
Labels: bug
