### ISSUE TITLE
`brew install ibm-cloud-cli` failing - Docker.app already exists

### ISSUE THREAD

**Issue by gcharters** [IBM-Cloud/ibm-cloud-cli-release#143] opened 2020-11-02 09:22 UTC
When trying to install ibm-cloud-cli using brew, it fails due to Docker.app already existing.  See below for the command and output.

brew install ibm-cloud-cli
Updating Homebrew...
==> Caveats
Cask ibm-cloud-cli installs files under /usr/local. The presence of such
files can cause warnings when running `brew doctor`, which is considered
to be a bug in Homebrew Cask.

==> Downloading https://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/1.2.3/IBM_Cloud_CLI_1.2.3.pkg
Already downloaded: /Users/charters/Library/Caches/Homebrew/downloads/6dbd843afcd4bacd0706f58e7df4af51f3c26965b2980af4a4cdca9c80defcfa--IBM_Cloud_CLI_1.2.3.pkg
==> Installing dependencies: docker
==> Downloading https://desktop.docker.com/mac/stable/48506/Docker.dmg
Already downloaded: /Users/charters/Library/Caches/Homebrew/downloads/9f0919492cb2c29dd0a102523544ac80a611db2302ce4322143a7bc6165cf17d--Docker.dmg
==> Verifying SHA-256 checksum for Cask 'docker'.
==> Installing Cask docker
==> Purging files for version 2.4.0.0,48506 of Cask docker
Error: It seems there is already an App at '/Applications/Docker.app'.
charters@Grahams-MBP ~ %

**Comment by archerzz** [comment] 2021-01-08 07:45
@gcharters We don't maintain the homebrew formula. The root cause should be that you've already installed a Docker app. It's a quite common issue in homebrew, and it can be fixed by adding `--force` (I could not find a better solution).
The dependency declaration of `ibm-cloud-cli` seems include too much

**Closed** 2021-08-31 13:35 UTC
